export const LIST_PRODUCTS_KEY = 'LIST_PRODUCTS';
export const LIST_PRODUCTS_BRANDS_KEY = 'LIST_PRODUCTS_BRANDS';
export const GET_PRODUCT_KEY = 'GET_PRODUCT';
export const GET_PRODUCTS_COUNT_KEY = 'GET_PRODUCT_COUNT';
export const GET_PRODUCTS_BY_BRAND_COUNT_KEY = 'GET_PRODUCT_BY_BRAND_COUNT';
